# Generated by Django 5.1.4 on 2024-12-30 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Work-From-Home', 'Work-From-Home')], max_length=50, verbose_name='Job Type')),
                ('short_description', models.TextField(verbose_name='Enter short description')),
                ('category', models.CharField(choices=[('Software Development', 'Software Development'), ('Data Engineering', 'Data Engineering'), ('Cloud Architecture', 'Cloud Architecture'), ('Cybersecurity', 'Cybersecurity'), ('DevOps', 'DevOps'), ('Network Engineering', 'Network Engineering'), ('AI & Machine Learning', 'AI & Machine Learning'), ('System Architecture', 'System Architecture'), ('Others', 'Others')], max_length=50)),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('full_description', models.TextField()),
                ('salary', models.CharField(max_length=50, verbose_name='Salary range')),
                ('qualifications', models.TextField(verbose_name='Enter qualifications')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
