# Generated by Django 5.1.4 on 2024-12-30 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_category_name_alter_job_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Data Engineering', 'Data Engineering'), ('Cloud Architecture', 'Cloud Architecture'), ('Cybersecurity', 'Cybersecurity'), ('DevOps', 'DevOps'), ('Network Engineering', 'Network Engineering'), ('AI & Machine Learning', 'AI & Machine Learning'), ('System Architecture', 'System Architecture'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(verbose_name='Enter qualifications'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=50, verbose_name='Salary range'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
