# Generated by Django 5.1.4 on 2024-12-30 09:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_category_alter_job_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='full_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
