# Generated by Django 5.1.4 on 2024-12-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_full_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='full_description',
            new_name='content',
        ),
    ]
